// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnUiUGuOSjdMQ7qVnBAXmOFY3PBOc4bK0',
    appId: '1:454165140976:web:7e5f8d0d35870785b33935',
    messagingSenderId: '454165140976',
    projectId: 'chat-app-b0136',
    authDomain: 'chat-app-b0136.firebaseapp.com',
    storageBucket: 'chat-app-b0136.appspot.com',
    measurementId: 'G-8L18P5Z8Q9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXRnXqodLdUD6wKepMo7pWBSc95vPn8AQ',
    appId: '1:454165140976:android:5b3bccce45770832b33935',
    messagingSenderId: '454165140976',
    projectId: 'chat-app-b0136',
    storageBucket: 'chat-app-b0136.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSBDkmNPUTSe6fkH4Vhc9WyL4GgjxiZ6s',
    appId: '1:454165140976:ios:a8736a3d6499a5beb33935',
    messagingSenderId: '454165140976',
    projectId: 'chat-app-b0136',
    storageBucket: 'chat-app-b0136.appspot.com',
    iosClientId: '454165140976-gq3dp6l23c3g89n7fbj1eeb7q2j1erhj.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSBDkmNPUTSe6fkH4Vhc9WyL4GgjxiZ6s',
    appId: '1:454165140976:ios:a8736a3d6499a5beb33935',
    messagingSenderId: '454165140976',
    projectId: 'chat-app-b0136',
    storageBucket: 'chat-app-b0136.appspot.com',
    iosClientId: '454165140976-gq3dp6l23c3g89n7fbj1eeb7q2j1erhj.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnUiUGuOSjdMQ7qVnBAXmOFY3PBOc4bK0',
    appId: '1:454165140976:web:23679715564f8bb0b33935',
    messagingSenderId: '454165140976',
    projectId: 'chat-app-b0136',
    authDomain: 'chat-app-b0136.firebaseapp.com',
    storageBucket: 'chat-app-b0136.appspot.com',
    measurementId: 'G-H0MNM8JD4P',
  );
}
